version: '2'
services:
    restaurante-app:
        image: restaurante
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://restaurante-postgresql:5432/restaurante
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    restaurante-postgresql:
        extends:
            file: postgresql.yml
            service: restaurante-postgresql
