version: '2'
services:
    restaurante-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/restaurante/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=restaurante
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
